---
Project0:
    Name: atac.lib
    Primer:
        - P1.09
    Round1:
        - R1.01
        - R1.02
        - R1.03
        - R1.04
        - R1.05
        - R1.06
        - R1.07
        - R1.08
        - R1.09
        - R1.10
        - R1.11
        - R1.12
        - R1.13
        - R1.14
        - R1.15
        - R1.16
        - R1.17
        - R1.18
        - R1.19
        - R1.20
        - R1.21
        - R1.22
        - R1.23
        - R1.24
        - R1.25
        - R1.26
        - R1.27
        - R1.28
        - R1.29
        - R1.30
        - R1.31
        - R1.32
        - R1.33
        - R1.34
        - R1.35
        - R1.36
        - R1.37
        - R1.38
        - R1.39
        - R1.40
        - R1.41
        - R1.42
        - R1.43
        - R1.44
        - R1.45
        - R1.46
        - R1.47
        - R1.48
        - R1.49
        - R1.50
        - R1.51
        - R1.52
        - R1.53
        - R1.54
        - R1.55
        - R1.56
        - R1.57
        - R1.58
        - R1.59
        - R1.60
        - R1.61
        - R1.62
        - R1.63
        - R1.64
        - R1.65
        - R1.66
        - R1.67
        - R1.68
        - R1.69
        - R1.70
        - R1.71
        - R1.72
        - R1.73
        - R1.74
        - R1.75
        - R1.76
        - R1.77
        - R1.78
        - R1.79
        - R1.80
        - R1.81
        - R1.82
        - R1.83
        - R1.84
        - R1.85
        - R1.86
        - R1.87
        - R1.88
        - R1.89
        - R1.90
        - R1.91
        - R1.92
        - R1.93
        - R1.94
        - R1.95
        - R1.96
Project1:
    Name: rna.lib
    Primer:
        - P1.17
    Round1:
        - R1.01
        - R1.02
        - R1.03
        - R1.04
        - R1.05
        - R1.06
        - R1.07
        - R1.08
        - R1.09
        - R1.10
        - R1.11
        - R1.12
        - R1.13
        - R1.14
        - R1.15
        - R1.16
        - R1.17
        - R1.18
        - R1.19
        - R1.20
        - R1.21
        - R1.22
        - R1.23
        - R1.24
        - R1.25
        - R1.26
        - R1.27
        - R1.28
        - R1.29
        - R1.30
        - R1.31
        - R1.32
        - R1.33
        - R1.34
        - R1.35
        - R1.36
        - R1.37
        - R1.38
        - R1.39
        - R1.40
        - R1.41
        - R1.42
        - R1.43
        - R1.44
        - R1.45
        - R1.46
        - R1.47
        - R1.48
        - R1.49
        - R1.50
        - R1.51
        - R1.52
        - R1.53
        - R1.54
        - R1.55
        - R1.56
        - R1.57
        - R1.58
        - R1.59
        - R1.60
        - R1.61
        - R1.62
        - R1.63
        - R1.64
        - R1.65
        - R1.66
        - R1.67
        - R1.68
        - R1.69
        - R1.70
        - R1.71
        - R1.72
        - R1.73
        - R1.74
        - R1.75
        - R1.76
        - R1.77
        - R1.78
        - R1.79
        - R1.80
        - R1.81
        - R1.82
        - R1.83
        - R1.84
        - R1.85
        - R1.86
        - R1.87
        - R1.88
        - R1.89
        - R1.90
        - R1.91
        - R1.92
        - R1.93
        - R1.94
        - R1.95
        - R1.96
...